package otg.bean;

import java.util.Date;

public class Challenge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.challenge_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer challengeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.challenge_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String challengeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.challenge_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String challengeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.challenge_descritpion
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String challengeDescritpion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.location_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date addDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.challenge_id
     *
     * @return the value of challenge.challenge_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getChallengeId() {
        return challengeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.challenge_id
     *
     * @param challengeId the value for challenge.challenge_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setChallengeId(Integer challengeId) {
        this.challengeId = challengeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.challenge_code
     *
     * @return the value of challenge.challenge_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getChallengeCode() {
        return challengeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.challenge_code
     *
     * @param challengeCode the value for challenge.challenge_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setChallengeCode(String challengeCode) {
        this.challengeCode = challengeCode == null ? null : challengeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.challenge_name
     *
     * @return the value of challenge.challenge_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getChallengeName() {
        return challengeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.challenge_name
     *
     * @param challengeName the value for challenge.challenge_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setChallengeName(String challengeName) {
        this.challengeName = challengeName == null ? null : challengeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.challenge_descritpion
     *
     * @return the value of challenge.challenge_descritpion
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getChallengeDescritpion() {
        return challengeDescritpion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.challenge_descritpion
     *
     * @param challengeDescritpion the value for challenge.challenge_descritpion
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setChallengeDescritpion(String challengeDescritpion) {
        this.challengeDescritpion = challengeDescritpion == null ? null : challengeDescritpion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.location_id
     *
     * @return the value of challenge.location_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.location_id
     *
     * @param locationId the value for challenge.location_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.add_date
     *
     * @return the value of challenge.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.add_date
     *
     * @param addDate the value for challenge.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.update_date
     *
     * @return the value of challenge.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.update_date
     *
     * @param updateDate the value for challenge.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}