package otg.bean;

import java.util.Date;

public class ChallengeOperation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge_operation.challenge_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer challengeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge_operation.operation_type
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String operationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge_operation.operation_desc
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String operationDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge_operation.operation_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date operationDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge_operation.challenge_id
     *
     * @return the value of challenge_operation.challenge_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getChallengeId() {
        return challengeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge_operation.challenge_id
     *
     * @param challengeId the value for challenge_operation.challenge_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setChallengeId(Integer challengeId) {
        this.challengeId = challengeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge_operation.operation_type
     *
     * @return the value of challenge_operation.operation_type
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge_operation.operation_type
     *
     * @param operationType the value for challenge_operation.operation_type
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge_operation.operation_desc
     *
     * @return the value of challenge_operation.operation_desc
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getOperationDesc() {
        return operationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge_operation.operation_desc
     *
     * @param operationDesc the value for challenge_operation.operation_desc
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setOperationDesc(String operationDesc) {
        this.operationDesc = operationDesc == null ? null : operationDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge_operation.operation_date
     *
     * @return the value of challenge_operation.operation_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getOperationDate() {
        return operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge_operation.operation_date
     *
     * @param operationDate the value for challenge_operation.operation_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }
}