package otg.bean;

import java.util.Date;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.direct_flag
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Boolean directFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.provience_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer provienceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date addDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_id
     *
     * @return the value of city.city_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_id
     *
     * @param cityId the value for city.city_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_code
     *
     * @return the value of city.city_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_code
     *
     * @param cityCode the value for city.city_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_name
     *
     * @return the value of city.city_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_name
     *
     * @param cityName the value for city.city_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.direct_flag
     *
     * @return the value of city.direct_flag
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Boolean getDirectFlag() {
        return directFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.direct_flag
     *
     * @param directFlag the value for city.direct_flag
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setDirectFlag(Boolean directFlag) {
        this.directFlag = directFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.provience_id
     *
     * @return the value of city.provience_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getProvienceId() {
        return provienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.provience_id
     *
     * @param provienceId the value for city.provience_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setProvienceId(Integer provienceId) {
        this.provienceId = provienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.add_date
     *
     * @return the value of city.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.add_date
     *
     * @param addDate the value for city.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.update_date
     *
     * @return the value of city.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.update_date
     *
     * @param updateDate the value for city.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}