package otg.bean;

import java.util.Date;

public class Code {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer codeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code_type
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String codeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String codeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code_value
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String codeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code_description
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String codeDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date addDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code_id
     *
     * @return the value of code.code_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code_id
     *
     * @param codeId the value for code.code_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setCodeId(Integer codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code_type
     *
     * @return the value of code.code_type
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code_type
     *
     * @param codeType the value for code.code_type
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code_name
     *
     * @return the value of code.code_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code_name
     *
     * @param codeName the value for code.code_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code_value
     *
     * @return the value of code.code_value
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getCodeValue() {
        return codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code_value
     *
     * @param codeValue the value for code.code_value
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue == null ? null : codeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code_description
     *
     * @return the value of code.code_description
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getCodeDescription() {
        return codeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code_description
     *
     * @param codeDescription the value for code.code_description
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setCodeDescription(String codeDescription) {
        this.codeDescription = codeDescription == null ? null : codeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.add_date
     *
     * @return the value of code.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.add_date
     *
     * @param addDate the value for code.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.update_date
     *
     * @return the value of code.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.update_date
     *
     * @param updateDate the value for code.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}