package otg.bean;

import java.util.Date;

public class District {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.district_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer districtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.district_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String districtCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.district_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String districtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.city_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date addDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.district_id
     *
     * @return the value of district.district_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.district_id
     *
     * @param districtId the value for district.district_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.district_code
     *
     * @return the value of district.district_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.district_code
     *
     * @param districtCode the value for district.district_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode == null ? null : districtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.district_name
     *
     * @return the value of district.district_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.district_name
     *
     * @param districtName the value for district.district_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.city_id
     *
     * @return the value of district.city_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.city_id
     *
     * @param cityId the value for district.city_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.add_date
     *
     * @return the value of district.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.add_date
     *
     * @param addDate the value for district.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.update_date
     *
     * @return the value of district.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.update_date
     *
     * @param updateDate the value for district.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}