package otg.bean;

import java.util.Date;

public class Domain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.domain_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer domainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.domain_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String domainCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.domain_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String domainName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date addDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.domain_id
     *
     * @return the value of domain.domain_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.domain_id
     *
     * @param domainId the value for domain.domain_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.domain_code
     *
     * @return the value of domain.domain_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getDomainCode() {
        return domainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.domain_code
     *
     * @param domainCode the value for domain.domain_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setDomainCode(String domainCode) {
        this.domainCode = domainCode == null ? null : domainCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.domain_name
     *
     * @return the value of domain.domain_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.domain_name
     *
     * @param domainName the value for domain.domain_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName == null ? null : domainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.add_date
     *
     * @return the value of domain.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.add_date
     *
     * @param addDate the value for domain.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.update_date
     *
     * @return the value of domain.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.update_date
     *
     * @param updateDate the value for domain.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}