package otg.bean;

import java.util.Date;

public class Location {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.location_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.location_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String locationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.location_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String locationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.district_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer districtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.longitude
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.latitude
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date addDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_id
     *
     * @return the value of location.location_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_id
     *
     * @param locationId the value for location.location_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_code
     *
     * @return the value of location.location_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getLocationCode() {
        return locationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_code
     *
     * @param locationCode the value for location.location_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode == null ? null : locationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_name
     *
     * @return the value of location.location_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_name
     *
     * @param locationName the value for location.location_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setLocationName(String locationName) {
        this.locationName = locationName == null ? null : locationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.district_id
     *
     * @return the value of location.district_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.district_id
     *
     * @param districtId the value for location.district_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.longitude
     *
     * @return the value of location.longitude
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.longitude
     *
     * @param longitude the value for location.longitude
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.latitude
     *
     * @return the value of location.latitude
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.latitude
     *
     * @param latitude the value for location.latitude
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.add_date
     *
     * @return the value of location.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.add_date
     *
     * @param addDate the value for location.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.update_date
     *
     * @return the value of location.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.update_date
     *
     * @param updateDate the value for location.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}