package otg.bean;

import java.util.Date;

public class OtgUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otg_user.uid
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otg_user.user_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otg_user.password
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otg_user.nick_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otg_user.age
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otg_user.gender
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otg_user.introduction
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otg_user.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date addDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otg_user.uid
     *
     * @return the value of otg_user.uid
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otg_user.uid
     *
     * @param uid the value for otg_user.uid
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otg_user.user_name
     *
     * @return the value of otg_user.user_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otg_user.user_name
     *
     * @param userName the value for otg_user.user_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otg_user.password
     *
     * @return the value of otg_user.password
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otg_user.password
     *
     * @param password the value for otg_user.password
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otg_user.nick_name
     *
     * @return the value of otg_user.nick_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otg_user.nick_name
     *
     * @param nickName the value for otg_user.nick_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otg_user.age
     *
     * @return the value of otg_user.age
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otg_user.age
     *
     * @param age the value for otg_user.age
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otg_user.gender
     *
     * @return the value of otg_user.gender
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otg_user.gender
     *
     * @param gender the value for otg_user.gender
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otg_user.introduction
     *
     * @return the value of otg_user.introduction
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otg_user.introduction
     *
     * @param introduction the value for otg_user.introduction
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otg_user.add_date
     *
     * @return the value of otg_user.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otg_user.add_date
     *
     * @param addDate the value for otg_user.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
}