package otg.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProvienceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public ProvienceExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProvienceIdIsNull() {
            addCriterion("provience_id is null");
            return (Criteria) this;
        }

        public Criteria andProvienceIdIsNotNull() {
            addCriterion("provience_id is not null");
            return (Criteria) this;
        }

        public Criteria andProvienceIdEqualTo(Integer value) {
            addCriterion("provience_id =", value, "provienceId");
            return (Criteria) this;
        }

        public Criteria andProvienceIdNotEqualTo(Integer value) {
            addCriterion("provience_id <>", value, "provienceId");
            return (Criteria) this;
        }

        public Criteria andProvienceIdGreaterThan(Integer value) {
            addCriterion("provience_id >", value, "provienceId");
            return (Criteria) this;
        }

        public Criteria andProvienceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("provience_id >=", value, "provienceId");
            return (Criteria) this;
        }

        public Criteria andProvienceIdLessThan(Integer value) {
            addCriterion("provience_id <", value, "provienceId");
            return (Criteria) this;
        }

        public Criteria andProvienceIdLessThanOrEqualTo(Integer value) {
            addCriterion("provience_id <=", value, "provienceId");
            return (Criteria) this;
        }

        public Criteria andProvienceIdIn(List<Integer> values) {
            addCriterion("provience_id in", values, "provienceId");
            return (Criteria) this;
        }

        public Criteria andProvienceIdNotIn(List<Integer> values) {
            addCriterion("provience_id not in", values, "provienceId");
            return (Criteria) this;
        }

        public Criteria andProvienceIdBetween(Integer value1, Integer value2) {
            addCriterion("provience_id between", value1, value2, "provienceId");
            return (Criteria) this;
        }

        public Criteria andProvienceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("provience_id not between", value1, value2, "provienceId");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeIsNull() {
            addCriterion("provience_code is null");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeIsNotNull() {
            addCriterion("provience_code is not null");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeEqualTo(String value) {
            addCriterion("provience_code =", value, "provienceCode");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeNotEqualTo(String value) {
            addCriterion("provience_code <>", value, "provienceCode");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeGreaterThan(String value) {
            addCriterion("provience_code >", value, "provienceCode");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("provience_code >=", value, "provienceCode");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeLessThan(String value) {
            addCriterion("provience_code <", value, "provienceCode");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeLessThanOrEqualTo(String value) {
            addCriterion("provience_code <=", value, "provienceCode");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeLike(String value) {
            addCriterion("provience_code like", value, "provienceCode");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeNotLike(String value) {
            addCriterion("provience_code not like", value, "provienceCode");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeIn(List<String> values) {
            addCriterion("provience_code in", values, "provienceCode");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeNotIn(List<String> values) {
            addCriterion("provience_code not in", values, "provienceCode");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeBetween(String value1, String value2) {
            addCriterion("provience_code between", value1, value2, "provienceCode");
            return (Criteria) this;
        }

        public Criteria andProvienceCodeNotBetween(String value1, String value2) {
            addCriterion("provience_code not between", value1, value2, "provienceCode");
            return (Criteria) this;
        }

        public Criteria andProvienceNameIsNull() {
            addCriterion("provience_name is null");
            return (Criteria) this;
        }

        public Criteria andProvienceNameIsNotNull() {
            addCriterion("provience_name is not null");
            return (Criteria) this;
        }

        public Criteria andProvienceNameEqualTo(String value) {
            addCriterion("provience_name =", value, "provienceName");
            return (Criteria) this;
        }

        public Criteria andProvienceNameNotEqualTo(String value) {
            addCriterion("provience_name <>", value, "provienceName");
            return (Criteria) this;
        }

        public Criteria andProvienceNameGreaterThan(String value) {
            addCriterion("provience_name >", value, "provienceName");
            return (Criteria) this;
        }

        public Criteria andProvienceNameGreaterThanOrEqualTo(String value) {
            addCriterion("provience_name >=", value, "provienceName");
            return (Criteria) this;
        }

        public Criteria andProvienceNameLessThan(String value) {
            addCriterion("provience_name <", value, "provienceName");
            return (Criteria) this;
        }

        public Criteria andProvienceNameLessThanOrEqualTo(String value) {
            addCriterion("provience_name <=", value, "provienceName");
            return (Criteria) this;
        }

        public Criteria andProvienceNameLike(String value) {
            addCriterion("provience_name like", value, "provienceName");
            return (Criteria) this;
        }

        public Criteria andProvienceNameNotLike(String value) {
            addCriterion("provience_name not like", value, "provienceName");
            return (Criteria) this;
        }

        public Criteria andProvienceNameIn(List<String> values) {
            addCriterion("provience_name in", values, "provienceName");
            return (Criteria) this;
        }

        public Criteria andProvienceNameNotIn(List<String> values) {
            addCriterion("provience_name not in", values, "provienceName");
            return (Criteria) this;
        }

        public Criteria andProvienceNameBetween(String value1, String value2) {
            addCriterion("provience_name between", value1, value2, "provienceName");
            return (Criteria) this;
        }

        public Criteria andProvienceNameNotBetween(String value1, String value2) {
            addCriterion("provience_name not between", value1, value2, "provienceName");
            return (Criteria) this;
        }

        public Criteria andDomainIdIsNull() {
            addCriterion("domain_id is null");
            return (Criteria) this;
        }

        public Criteria andDomainIdIsNotNull() {
            addCriterion("domain_id is not null");
            return (Criteria) this;
        }

        public Criteria andDomainIdEqualTo(Integer value) {
            addCriterion("domain_id =", value, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdNotEqualTo(Integer value) {
            addCriterion("domain_id <>", value, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdGreaterThan(Integer value) {
            addCriterion("domain_id >", value, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("domain_id >=", value, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdLessThan(Integer value) {
            addCriterion("domain_id <", value, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdLessThanOrEqualTo(Integer value) {
            addCriterion("domain_id <=", value, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdIn(List<Integer> values) {
            addCriterion("domain_id in", values, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdNotIn(List<Integer> values) {
            addCriterion("domain_id not in", values, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdBetween(Integer value1, Integer value2) {
            addCriterion("domain_id between", value1, value2, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdNotBetween(Integer value1, Integer value2) {
            addCriterion("domain_id not between", value1, value2, "domainId");
            return (Criteria) this;
        }

        public Criteria andAddDateIsNull() {
            addCriterion("add_date is null");
            return (Criteria) this;
        }

        public Criteria andAddDateIsNotNull() {
            addCriterion("add_date is not null");
            return (Criteria) this;
        }

        public Criteria andAddDateEqualTo(Date value) {
            addCriterion("add_date =", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotEqualTo(Date value) {
            addCriterion("add_date <>", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateGreaterThan(Date value) {
            addCriterion("add_date >", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateGreaterThanOrEqualTo(Date value) {
            addCriterion("add_date >=", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLessThan(Date value) {
            addCriterion("add_date <", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLessThanOrEqualTo(Date value) {
            addCriterion("add_date <=", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateIn(List<Date> values) {
            addCriterion("add_date in", values, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotIn(List<Date> values) {
            addCriterion("add_date not in", values, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateBetween(Date value1, Date value2) {
            addCriterion("add_date between", value1, value2, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotBetween(Date value1, Date value2) {
            addCriterion("add_date not between", value1, value2, "addDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table provience
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 28 22:15:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table provience
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}