package otg.bean;

import java.util.Date;

public class Provience {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provience.provience_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer provienceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provience.provience_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String provienceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provience.provience_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private String provienceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provience.domain_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer domainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provience.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date addDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provience.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provience.provience_id
     *
     * @return the value of provience.provience_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getProvienceId() {
        return provienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provience.provience_id
     *
     * @param provienceId the value for provience.provience_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setProvienceId(Integer provienceId) {
        this.provienceId = provienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provience.provience_code
     *
     * @return the value of provience.provience_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getProvienceCode() {
        return provienceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provience.provience_code
     *
     * @param provienceCode the value for provience.provience_code
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setProvienceCode(String provienceCode) {
        this.provienceCode = provienceCode == null ? null : provienceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provience.provience_name
     *
     * @return the value of provience.provience_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public String getProvienceName() {
        return provienceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provience.provience_name
     *
     * @param provienceName the value for provience.provience_name
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setProvienceName(String provienceName) {
        this.provienceName = provienceName == null ? null : provienceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provience.domain_id
     *
     * @return the value of provience.domain_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provience.domain_id
     *
     * @param domainId the value for provience.domain_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provience.add_date
     *
     * @return the value of provience.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provience.add_date
     *
     * @param addDate the value for provience.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provience.update_date
     *
     * @return the value of provience.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provience.update_date
     *
     * @param updateDate the value for provience.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}