package otg.bean;

import java.util.Date;

public class UserChallenge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_challenge.uc_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer ucId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_challenge.uid
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_challenge.challenge_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer challengeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_challenge.support
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Integer support;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_challenge.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date addDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_challenge.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_challenge.uc_id
     *
     * @return the value of user_challenge.uc_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getUcId() {
        return ucId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_challenge.uc_id
     *
     * @param ucId the value for user_challenge.uc_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setUcId(Integer ucId) {
        this.ucId = ucId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_challenge.uid
     *
     * @return the value of user_challenge.uid
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_challenge.uid
     *
     * @param uid the value for user_challenge.uid
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_challenge.challenge_id
     *
     * @return the value of user_challenge.challenge_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getChallengeId() {
        return challengeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_challenge.challenge_id
     *
     * @param challengeId the value for user_challenge.challenge_id
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setChallengeId(Integer challengeId) {
        this.challengeId = challengeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_challenge.support
     *
     * @return the value of user_challenge.support
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Integer getSupport() {
        return support;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_challenge.support
     *
     * @param support the value for user_challenge.support
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setSupport(Integer support) {
        this.support = support;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_challenge.add_date
     *
     * @return the value of user_challenge.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_challenge.add_date
     *
     * @param addDate the value for user_challenge.add_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_challenge.update_date
     *
     * @return the value of user_challenge.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_challenge.update_date
     *
     * @param updateDate the value for user_challenge.update_date
     *
     * @mbg.generated Sat Dec 28 22:15:09 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}